[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache/foundry"
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
libs = ["node_modules", "../../node_modules"]
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
